### ISSUE TITLE
Install Guide

### ISSUE THREAD

**Issue by jhemmmm** [suconghou/fastloadjs#1]
Hello,

Is there any installation guide for this project?. There's seems to be missing a lot of packages.

**Comment by jhemmmm** [comment]
Was able to make it work somehow, but, the video doesn't play. Fetching the video seems to be working perfectly fine thou.
https://i.imgur.com/M0tOWLi.png

I have also the correct codec.

**Comment by suconghou** [comment]
it works as a part of https://github.com/suconghou/u2web , you can see the demo in u2web for more information

**Comment by jhemmmm** [comment]
> 

yeah, but I'm trying to run it to be independent. Here's what I have right now,
https://i.imgur.com/Eoc6zw7.png

the configuration seems to be correct, but, the video doesn't play like on the demo.
https://i.imgur.com/z3F5W2s.png

**Comment by suconghou** [comment]
you missed some config , I have create a demo for you , see the demo folder, by the way , u2web project already has an independent web component  player.

**Comment by jhemmmm** [comment]
> you missed some config , I have create a demo for you , see the demo folder, by the way , u2web project already has an independent web component player.

Works like a charm, well, this project is much more readable than the u2web project, it's easy to re-code to make it work on other projects too. And another question.

I have a normal mp4 URL file on my local, is there any possible way to parse and get the "init,index" object without inputting it manually?.

**Comment by suconghou** [comment]
1. your mp4 file should be Fragmented mp4 
2. you should write server side code to parse the mp4 file info, you can search some libraries such as https://github.com/edgeware/mp4ff to parse the mp4 box

**Comment by jhemmmm** [comment]
> 1. your mp4 file should be Fragmented mp4
> 2. you should write server side code to parse the mp4 file info, you can search some libraries such as https://github.com/edgeware/mp4ff to parse the mp4 box

I noticed on the code, but, wasn't youtube is not a fragmented mp4?.

**Comment by suconghou** [comment]
it is Fragmented , only Itag 17,18,22 is not  fragmented and contains both audio and video.
If you does not use fragmented, may be you should use hls.

**Comment by jhemmmm** [comment]
> it is Fragmented , only Itag 17,18,22 is not fragmented and contains both audio and video. If you does not use fragmented, may be you should use hls.

You're right, in that case, do you think we could implement this:
https://github.com/gpac/mp4box.js

I saw a website that streams over Websocket and they somehow use this project to stream the mp4 video file via HMLT5.

**Comment by suconghou** [comment]
yes, It is possible, we can use range request to fetch the first 500kb and parse the data use javascript

**Comment by jhemmmm** [comment]
> 

I have contacted you via mail, let me know if you're up for it. :)
